### ISSUE TITLE
prebuilt native images

### ISSUE THREAD

**Issue by laughedelic** [mroth/scalafmt-native#9]
I think Scalafmt now has prebuilt native images:
- https://scalameta.org/scalafmt/docs/installation.html#native-image
- https://github.com/scalameta/scalafmt/releases/latest (see Assets)

I don't know if your way of building the native image has some advantages over those prebuilt, but I just wanted to bring this to your attention in case it can simplify things here.

**Comment by mroth** [comment]
@laughedelic that's true, in fact the official images were based on the work in this repo! I haven't tested them myself but now that they exist it makes sense to wind this repository down.
